### ISSUE TITLE
Im using Mediocre Map Assistant 2 but whenever I open the editor it closes after around 30-60 seconds.

### ISSUE THREAD

**Issue by AccurateFranky** [bsmg/wiki#287]

**Comment by bloodcloak** [comment]
Hello! There is a troubleshooting step on the MMA2 user guide that addresses this! https://bsmg.wiki/mapping/mediocre-map-assistant.html#my-song-is-stuck-loading-in-the-editor-forever-or-returns-to-the-edit-song-screen-after-briefly-loading 

If you need any additional assistance with getting up and running please visit the `#mapping-discussion` channel of our Discord! https://discord.gg/beatsabermods
