### ISSUE TITLE
Add a section about error checking

### ISSUE THREAD

**Issue by Scarladore** [bsmg/wiki#346]
I am a new mapper and I followed along this wiki page https://bsmg.wiki/mapping/
Once I felt I was ready to post my song in the Beat Saber Modding Discord, I was told to error check my map using SHIFT + TAB in MMA2, and to use Parity Checker and Map Check.
It would have been very useful if that wiki page had contained a section in the PlayTesting section about error checking before posting a map in the discord, as this is the first thing playtesters will tell you to do anyways.

Please consider adding a error checking section to this wiki page.

**Comment by bloodcloak** [comment]
A small note has been added to the warning in the third party testing section as of pr #394 

Thanks for the suggestion
