### ISSUE TITLE
Language localization / translation

### ISSUE THREAD

**Issue by megalon** [bsmg/wiki#35]
**Issue**
It would be nice to translate the wiki into other languages.
What would be the best way to do this with the wiki?

**Suggestions**
The simplest approach to this would be to just have a subfolder for the different languages, then use subdomains to access these different folders.

```
wiki
L en
L jp
L ...
```

`en` -> `bsmg.wiki` / `en.bsmg.wiki`
`jp` -> `jp.bsmg.wiki` 
Etc...

**Comment by bloodcloak** [comment]
using locales built in to vuepress. Crowdin solution in progress.
