### ISSUE TITLE
How to calculate a song hash?

### ISSUE THREAD

**Issue by fs19910227** [bsmg/wiki#395]
Sorry to bother you.
I want to delete songs which not in the playlist.
But, I don't know  the detail how the song's hash is calculated, so I can't establish a correspondence between songs and songs lists.
Thank you very much for your advice.

**Comment by bloodcloak** [comment]
According to a message in the #pc-mod-dev channel in BSMG a song hash is the sha-1 hash of the info.dat and its difficulty dat files in order they appear in the info.dat file. You can take a look at how other programs/mods do it such as SongCore or BeatSaver to double check.

If you just want to manage your playlist the section for map management software was just updated with tools https://bsmg.wiki/faq/#song-management-tools

Hope this helps
