### ISSUE TITLE
Request adding a note about SiraUtil.json

### ISSUE THREAD

**Issue by thefinalwolf** [bsmg/wiki#403]
Might want to add a note that editing the **SiraUtil.json** file won't be necessary if the 'Enabled' options don't exist. I was following the tut and saw the options weren't there, so I tried running the game anyways and all the features worked fine. 
https://github.com/bsmg/wiki/blob/2b7053be8adaa465bdf20a5adf39dfe9aae52492/wiki/mapping/basic-lighting.md?plain=1#L215

**Comment by bloodcloak** [comment]
Has been fixed in #399
