### ISSUE TITLE
More languages needed! 

### ISSUE THREAD

**Issue by fred913** [bsmg/wiki#454]
Are other languages' translations welcomed? If so, how can I make the file tree to do the translation work (directories and files to be copied, etc.)? I **already** understand the steps to create a PR. 

Also, I mean the wiki itself, not MMA2.

**Comment by FranciscoRibeiro03** [comment]
There are a lot of people dedicated on translating the wiki. You can apply to help on [this form](https://forms.gle/e3BqA3poMjESARe76)

**Comment by fred913** [comment]
Thank you for the early reply! I'll check it out soon, and contribute to
the wiki soon.

Francisco Ribeiro ***@***.***> 于 2022年8月9日周二 下午9:15写道：

**Comment by fred913** [comment]
I've sent the request. This issue will be closed soon.

Francisco Ribeiro ***@***.***> 于 2022年8月9日周二 下午9:15写道：
