### ISSUE TITLE
Remove documentation of MMA2 key bindings

### ISSUE THREAD

**Issue by mcendu** [bsmg/wiki#499]
While undertaking the project of documenting v2 and v3 lighting (#497), the linter complained about the length of lines after I added official editor keybinds in 048e71693217b6887753891050d9c42104acd9f2:

```console
$ yarn lint
./wiki/mapping/editor-keybinds.md:23:121 MD013/line-length Line length [Expected: 120; Actual: 131]
./wiki/mapping/editor-keybinds.md:25:121 MD013/line-length Line length [Expected: 120; Actual: 131]
./wiki/mapping/editor-keybinds.md:26:121 MD013/line-length Line length [Expected: 120; Actual: 131]
...
./wiki/mapping/editor-keybinds.md:37:121 MD013/line-length Line length [Expected: 120; Actual: 127]
./wiki/mapping/editor-keybinds.md:39:121 MD013/line-length Line length [Expected: 120; Actual: 127]
./wiki/mapping/editor-keybinds.md:40:121 MD013/line-length Line length [Expected: 120; Actual: 127]
./wiki/mapping/editor-keybinds.md:41:121 MD013/line-length Line length [Expected: 120; Actual: 127]
./wiki/mapping/editor-keybinds.md:44:121 MD013/line-length Line length [Expected: 120; Actual: 141]
./wiki/mapping/editor-keybinds.md:46:121 MD013/line-length Line length [Expected: 120; Actual: 141]
./wiki/mapping/editor-keybinds.md:47:121 MD013/line-length Line length [Expected: 120; Actual: 141]
...
```

While I temporarily worked around this by disabling MD013 for the file, I think that it might be now time to remove documentation for keybinds for Mediocre Map Assistant 2 (MMA2). MMA2 has been unmaintained since its last release about one year ago, and most users have moved on to other editors, for instance Chromapper. More discussion would be needed to decide if we should undocument MMA2 keybinds, though.

[Here is a patch against #497 that does the job.](https://github.com/bsmg/wiki/files/11469208/0001-remove-mma2-keybinds.patch)

**Comment by bloodcloak** [comment]
Would probably be better to move CM to the first column in the tables instead of outright removing.

New order being CM, mma2, beatmapper

**Comment by mcendu** [comment]
> New order being CM, mma2, beatmapper

What about official editor? I would like to suggest the order CM, official, mma2 and beatmapper

**Comment by mcendu** [comment]
Leaving this open because this might be relevant later

**Comment by mcendu** [comment]
Reopen when someone files a duplicate
