### ISSUE TITLE
All Sites in the root directory without a custom sitemap use the Quest Modding sitemap

### ISSUE THREAD

**Issue by hdgamer1404Jonas** [bsmg/wiki#538]
Ive noticed that the following sites use the sitemap (the navigation menu on the left) from the Quest Modding Part of the wiki.
https://bsmg.wiki/beginners-guide.html
https://bsmg.wiki/pc-modding.html
https://bsmg.wiki/grips-and-tricks.html

It seems to affect all sites in the root directory of the folder with the markdown files

**Comment by bloodcloak** [comment]
Thanks, addressed in #540
