### ISSUE TITLE
Beat Saber not showing anything after logo loading

### ISSUE THREAD

**Issue by DavidPaf** [bsmg/wiki#569]
Beat Saber not showing anything after logo loading.

I followed the steps to mod beat saber using questpatcher on quest 3: https://bsmg.wiki/quest-modding.html#questpatcher

however, when I launch the app, after loading the Beat Saber logo, nothing shows up.

**Comment by IAMDEDJUSTTOGETFILES** [comment]
You can still exit the game normally, right?
